module.exports.playerSeeds = [
    {
        "PlayerID": 50001467,
        "FirstName": "Carl",
        "LastName": "Tucker",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 86,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Senior",
        "Height": 74,
        "Weight": 248,
        "BirthCity": "Concord",
        "BirthState": "NC",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2016-08-23T02:18:45",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50011522,
        "FirstName": "Drew",
        "LastName": "Kobayashi",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 85,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Senior",
        "Height": 74,
        "Weight": 200,
        "BirthCity": "Honolulu",
        "BirthState": "HI",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2016-08-23T11:57:48",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50013241,
        "FirstName": "Ben",
        "LastName": "Davis",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 1,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Senior",
        "Height": 76,
        "Weight": 250,
        "BirthCity": "Gordo",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2016-08-23T12:02:42",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50013295,
        "FirstName": "Joshua",
        "LastName": "McMillon",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 40,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Senior",
        "Height": 75,
        "Weight": 240,
        "BirthCity": "Memphis",
        "BirthState": "TN",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2016-08-23T12:02:43",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50013335,
        "FirstName": "Chris",
        "LastName": "Owens",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 79,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Senior",
        "Height": 75,
        "Weight": 315,
        "BirthCity": "Arlington",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2016-08-23T12:02:44",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50018126,
        "FirstName": "Logan",
        "LastName": "Burnett",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 12,
        "Position": "QB",
        "PositionCategory": "OFF",
        "Class": "Senior",
        "Height": 74,
        "Weight": 200,
        "BirthCity": "Pelham",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2016-08-30T18:58:36",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027547,
        "FirstName": "Daniel",
        "LastName": "Wright",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 3,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 73,
        "Weight": 195,
        "BirthCity": "Fort Lauderdale",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:25:58",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027548,
        "FirstName": "Christopher",
        "LastName": "Allen",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 4,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 76,
        "Weight": 250,
        "BirthCity": "Baton Rouge",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:25:59",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027559,
        "FirstName": "Brian",
        "LastName": "Robinson Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 4,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Senior",
        "Height": 73,
        "Weight": 228,
        "BirthCity": "Tuscaloosa",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:26:11",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027575,
        "FirstName": "Kendall",
        "LastName": "Randolph",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 85,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Junior",
        "Height": 76,
        "Weight": 298,
        "BirthCity": "Madison",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:26:28",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027580,
        "FirstName": "Major",
        "LastName": "Tennison",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 88,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Junior",
        "Height": 77,
        "Weight": 252,
        "BirthCity": "Flint",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:26:33",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027581,
        "FirstName": "LaBryan",
        "LastName": "Ray",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 18,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 77,
        "Weight": 295,
        "BirthCity": "Madison",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:26:34",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027582,
        "FirstName": "Phidarian",
        "LastName": "Mathis",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 48,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 76,
        "Weight": 312,
        "BirthCity": "Wisner",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:26:35",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50027584,
        "FirstName": "Joseph",
        "LastName": "Bulovas",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 97,
        "Position": "K",
        "PositionCategory": "ST",
        "Class": "Junior",
        "Height": 72,
        "Weight": 215,
        "BirthCity": "Mandeville",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-07-24T03:26:37",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50033526,
        "FirstName": "Kyle",
        "LastName": "Edwards",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 27,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 209,
        "BirthCity": "Destrehan",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-09-01T03:42:51",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50033840,
        "FirstName": "Charlie",
        "LastName": "Scott",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 85,
        "Position": "P",
        "PositionCategory": "ST",
        "Class": "Senior",
        "Height": 73,
        "Weight": 195,
        "BirthCity": "Greenwood Village",
        "BirthState": "CO",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2017-09-02T03:29:10",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50037291,
        "FirstName": "Ale",
        "LastName": "Kaho",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 10,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 73,
        "Weight": 235,
        "BirthCity": "Reno",
        "BirthState": "NV",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-07-17T03:38:07",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50037469,
        "FirstName": "Skyler",
        "LastName": "DeLong",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 12,
        "Position": "P",
        "PositionCategory": "ST",
        "Class": "Junior",
        "Height": 76,
        "Weight": 188,
        "BirthCity": "Fort Mill",
        "BirthState": "SC",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-07-17T03:41:34",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50037471,
        "FirstName": "Jarez",
        "LastName": "Parks",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 23,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 76,
        "Weight": 240,
        "BirthCity": "Fellsmere",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-07-17T03:41:36",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50037472,
        "FirstName": "Slade",
        "LastName": "Bolden",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 18,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 71,
        "Weight": 191,
        "BirthCity": "West Monroe",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-07-17T03:41:37",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50037483,
        "FirstName": "Stephon",
        "LastName": "Wynn Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 90,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 76,
        "Weight": 310,
        "BirthCity": "Anderson",
        "BirthState": "SC",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-07-17T03:41:48",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041833,
        "FirstName": "Braxton",
        "LastName": "Barker",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 7,
        "Position": "QB",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 202,
        "BirthCity": "Birmingham",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:34",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041835,
        "FirstName": "Xavier",
        "LastName": "Williams",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 3,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 190,
        "BirthCity": "Hollywood",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:36",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041837,
        "FirstName": "Jalyn",
        "LastName": "Armour-Davis",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 5,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 192,
        "BirthCity": "Mobile",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:38",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041838,
        "FirstName": "Eddie",
        "LastName": "Smith",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 15,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 72,
        "Weight": 196,
        "BirthCity": "Slidell",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:39",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041840,
        "FirstName": "Josh",
        "LastName": "Jobe",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 28,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 73,
        "Weight": 192,
        "BirthCity": "Miami",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:41",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041845,
        "FirstName": "Jaylen",
        "LastName": "Moody",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 42,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 74,
        "Weight": 225,
        "BirthCity": "Conway",
        "BirthState": "SC",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:46",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041846,
        "FirstName": "Cameron",
        "LastName": "Latu",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 81,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 77,
        "Weight": 250,
        "BirthCity": "Salt Lake City",
        "BirthState": "UT",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:47",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041848,
        "FirstName": "Emil",
        "LastName": "Ekiyor Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 55,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 75,
        "Weight": 324,
        "BirthCity": "Indianapolis",
        "BirthState": "IN",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:49",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041849,
        "FirstName": "Joe",
        "LastName": "Donald",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 57,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Senior",
        "Height": 75,
        "Weight": 216,
        "BirthCity": "Mountain Brook",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:50",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041852,
        "FirstName": "Jackson",
        "LastName": "Roby",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 62,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Junior",
        "Height": 77,
        "Weight": 285,
        "BirthCity": "Huntsville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:53",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041853,
        "FirstName": "Tommy",
        "LastName": "Brown",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 75,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 79,
        "Weight": 320,
        "BirthCity": "Santa Ana",
        "BirthState": "CA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:54",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50041854,
        "FirstName": "Michael",
        "LastName": "Parker",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 80,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 78,
        "Weight": 232,
        "BirthCity": "Huntsville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2018-08-07T03:22:55",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045786,
        "FirstName": "Marcus",
        "LastName": "Banks",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 26,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 72,
        "Weight": 180,
        "BirthCity": "Houston",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:28:04",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045787,
        "FirstName": "Jordan",
        "LastName": "Battle",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 9,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 210,
        "BirthCity": "Fort Lauderdale",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:28:21",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045788,
        "FirstName": "Jahleel",
        "LastName": "Billingsley",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 19,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 76,
        "Weight": 230,
        "BirthCity": "Chicago",
        "BirthState": "IL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:28:24",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045789,
        "FirstName": "Cooper",
        "LastName": "Bishop",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 35,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 195,
        "BirthCity": "Vestavia Hills",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:28:26",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045790,
        "FirstName": "Tanner",
        "LastName": "Bowles",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 51,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 77,
        "Weight": 293,
        "BirthCity": "Glasgow",
        "BirthState": "KY",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:29:24",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045794,
        "FirstName": "Darrian",
        "LastName": "Dalcourt",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 71,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 75,
        "Weight": 300,
        "BirthCity": "Havre De Grace",
        "BirthState": "MD",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:33:05",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045795,
        "FirstName": "D.J.",
        "LastName": "Dale",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 94,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 75,
        "Weight": 307,
        "BirthCity": "Birmingham",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:34:01",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045796,
        "FirstName": "DJ",
        "LastName": "Douglas",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 25,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 202,
        "BirthCity": "Montgomery",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:35:36",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045797,
        "FirstName": "Justin",
        "LastName": "Eboigbe",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 92,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 77,
        "Weight": 285,
        "BirthCity": "Forest Park",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:43",
        "Created": "2019-07-30T15:35:43",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045798,
        "FirstName": "Rowdy",
        "LastName": "Garza",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 63,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 76,
        "Weight": 312,
        "BirthCity": "Trussville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:36:05",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045799,
        "FirstName": "A.J.",
        "LastName": "Gates",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 43,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 67,
        "Weight": 170,
        "BirthCity": "Mountain Brook",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:29",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045800,
        "FirstName": "Jayden",
        "LastName": "George",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 16,
        "Position": "QB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 192,
        "BirthCity": "Indianapolis",
        "BirthState": "IN",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:37",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045801,
        "FirstName": "Jake",
        "LastName": "Hall",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 59,
        "Position": "LS",
        "PositionCategory": "ST",
        "Class": "Sophomore",
        "Height": 75,
        "Weight": 238,
        "BirthCity": "Saraland",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:41",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045802,
        "FirstName": "Christian",
        "LastName": "Harris",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 8,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 74,
        "Weight": 232,
        "BirthCity": "Baton Rouge",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:45",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045803,
        "FirstName": "Kevin",
        "LastName": "Harris II",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 44,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 228,
        "BirthCity": "Loganville",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:53",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045804,
        "FirstName": "DeMarcco",
        "LastName": "Hellams",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 29,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 208,
        "BirthCity": "Washington",
        "BirthState": "DC",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:56",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045805,
        "FirstName": "Stone",
        "LastName": "Hollenbach",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 19,
        "Position": "QB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 208,
        "BirthCity": "Catawissa",
        "BirthState": "PA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:38:59",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045806,
        "FirstName": "Richard",
        "LastName": "Hunt",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 83,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 79,
        "Weight": 235,
        "BirthCity": "Memphis",
        "BirthState": "TN",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:02",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045807,
        "FirstName": "Braylen",
        "LastName": "Ingraham",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 52,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 289,
        "BirthCity": "Fort Lauderdale",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:05",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045808,
        "FirstName": "Amari",
        "LastName": "Kight",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 78,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 79,
        "Weight": 318,
        "BirthCity": "Alabaster",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:07",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045809,
        "FirstName": "Grant",
        "LastName": "Krieger",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 89,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 74,
        "Weight": 192,
        "BirthCity": "Pittsburgh",
        "BirthState": "PA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:09",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045810,
        "FirstName": "Shane",
        "LastName": "Lee",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 35,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 72,
        "Weight": 240,
        "BirthCity": "Burtonsville",
        "BirthState": "MD",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:44",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045811,
        "FirstName": "Julian",
        "LastName": "Lowenstein",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 49,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 201,
        "BirthCity": "Sarasota",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:46",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045812,
        "FirstName": "Jack",
        "LastName": "Martin",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 95,
        "Position": "P",
        "PositionCategory": "ST",
        "Class": "Sophomore",
        "Height": 72,
        "Weight": 206,
        "BirthCity": "Mobile",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:50",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045813,
        "FirstName": "John",
        "LastName": "Metchie",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 8,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 72,
        "Weight": 195,
        "BirthCity": "Brampton",
        "BirthState": "ON",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:39:54",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045815,
        "FirstName": "King",
        "LastName": "Mwikuta",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 30,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 77,
        "Weight": 238,
        "BirthCity": "West Point",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:01",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045816,
        "FirstName": "Evan",
        "LastName": "Neal",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 73,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 79,
        "Weight": 360,
        "BirthCity": "Okeechobee",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:03",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045817,
        "FirstName": "Ty",
        "LastName": "Perine",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 99,
        "Position": "P",
        "PositionCategory": "ST",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 218,
        "BirthCity": "Prattville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:05",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045819,
        "FirstName": "Gabe",
        "LastName": "Pugh",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 50,
        "Position": "LS",
        "PositionCategory": "ST",
        "Class": "Freshman",
        "Height": 77,
        "Weight": 273,
        "BirthCity": "Tuscaloosa",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:08",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045820,
        "FirstName": "Pierce",
        "LastName": "Quick",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 72,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 77,
        "Weight": 280,
        "BirthCity": "Trussville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:12",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045821,
        "FirstName": "Sam",
        "LastName": "Reed",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 42,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 165,
        "BirthCity": "Mountain Brook",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:15",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045822,
        "FirstName": "Will",
        "LastName": "Reichard",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 16,
        "Position": "K",
        "PositionCategory": "ST",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 190,
        "BirthCity": "Hoover",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:19",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045823,
        "FirstName": "Joshua",
        "LastName": "Robinson",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 27,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 69,
        "Weight": 180,
        "BirthCity": "Hoover",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:21",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045824,
        "FirstName": "Keilan",
        "LastName": "Robinson",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 2,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Sophomore",
        "Height": 69,
        "Weight": 190,
        "BirthCity": "Washington",
        "BirthState": "DC",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:26",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045825,
        "FirstName": "Trey",
        "LastName": "Sanders",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 24,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 214,
        "BirthCity": "Port Saint Joe",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:33",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045826,
        "FirstName": "Tripp",
        "LastName": "Slyman",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 93,
        "Position": "K",
        "PositionCategory": "ST",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 180,
        "BirthCity": "Huntsville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:34",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045828,
        "FirstName": "Ishmael",
        "LastName": "Sopsher",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 95,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 310,
        "BirthCity": "Amite",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:39",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045829,
        "FirstName": "Christian",
        "LastName": "Swann",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 46,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Senior",
        "Height": 69,
        "Weight": 179,
        "BirthCity": "Mableton",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:41",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045830,
        "FirstName": "Brandon",
        "LastName": "Turnage",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 7,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 73,
        "Weight": 186,
        "BirthCity": "Oxford",
        "BirthState": "MS",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:51",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045831,
        "FirstName": "Paul",
        "LastName": "Tyson",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 15,
        "Position": "QB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 77,
        "Weight": 228,
        "BirthCity": "Trussville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:40:54",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50045833,
        "FirstName": "Byron",
        "LastName": "Young",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 47,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 75,
        "Weight": 292,
        "BirthCity": "Laurel",
        "BirthState": "MS",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-07-30T15:41:02",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50048091,
        "FirstName": "Melvin",
        "LastName": "Billingsley",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 46,
        "Position": "TE",
        "PositionCategory": "OFF",
        "Class": "Junior",
        "Height": 75,
        "Weight": 230,
        "BirthCity": "Opelika",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-08-13T12:08:04",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50048092,
        "FirstName": "Joshua",
        "LastName": "Lanier",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 84,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Senior",
        "Height": 71,
        "Weight": 160,
        "BirthCity": "Tuscaloosa",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-08-13T12:08:13",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50050357,
        "FirstName": "Landon",
        "LastName": "Bothwell",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 96,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 71,
        "Weight": 220,
        "BirthCity": "Oneonta",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-08-21T13:49:51",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50050358,
        "FirstName": "Carson",
        "LastName": "Ware",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 39,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 73,
        "Weight": 190,
        "BirthCity": "Muscle Shoals",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2019-08-21T13:49:58",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054497,
        "FirstName": "Traeshon",
        "LastName": "Holden",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 11,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 208,
        "BirthCity": "Kissimmee",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T11:19:24",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054498,
        "FirstName": "Thaiu",
        "LastName": "Jones-Bell",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 14,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 190,
        "BirthCity": "Hallandale",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T11:19:33",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054499,
        "FirstName": "Jase",
        "LastName": "McClellan",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 21,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 71,
        "Weight": 212,
        "BirthCity": "Aledo",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T11:19:42",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054500,
        "FirstName": "Roydell",
        "LastName": "Williams",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 23,
        "Position": "RB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 70,
        "Weight": 210,
        "BirthCity": "Hueytown",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T11:19:48",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054501,
        "FirstName": "Bryce",
        "LastName": "Young",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 9,
        "Position": "QB",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 194,
        "BirthCity": "Pasadena",
        "BirthState": "CA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T11:19:57",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054639,
        "FirstName": "Will",
        "LastName": "Anderson Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 31,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 235,
        "BirthCity": "Hampton",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:04:38",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054640,
        "FirstName": "Matthew",
        "LastName": "Barnhill",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 53,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Sophomore",
        "Height": 73,
        "Weight": 209,
        "BirthCity": "Woodway",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:04:46",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054641,
        "FirstName": "Chris",
        "LastName": "Braswell",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 41,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 220,
        "BirthCity": "Baltimore",
        "BirthState": "MD",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:05:14",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054642,
        "FirstName": "Jackson",
        "LastName": "Bratton",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 33,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 225,
        "BirthCity": "Muscle Shoals",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:05:19",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054643,
        "FirstName": "Jalen",
        "LastName": "Edwards",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 38,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 177,
        "BirthCity": "Columbus",
        "BirthState": "MS",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:05:26",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054645,
        "FirstName": "Demouy",
        "LastName": "Kennedy",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 37,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 215,
        "BirthCity": "Theodore",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:05:48",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054646,
        "FirstName": "Seth",
        "LastName": "McLaughlin",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 56,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 280,
        "BirthCity": "Buford",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:06:00",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054647,
        "FirstName": "Jahquez",
        "LastName": "Robinson",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 21,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 74,
        "Weight": 190,
        "BirthCity": "Jacksonville",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:06:17",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054648,
        "FirstName": "Drew",
        "LastName": "Sanders",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 20,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 77,
        "Weight": 230,
        "BirthCity": "Denton",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:06:25",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50054649,
        "FirstName": "Ronald",
        "LastName": "Williams Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 22,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 74,
        "Weight": 190,
        "BirthCity": "Ferriday",
        "BirthState": "LA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-07-17T12:08:16",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057773,
        "FirstName": "Javon",
        "LastName": "Baker",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 5,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 74,
        "Weight": 195,
        "BirthCity": "Powder Springs",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-15T00:58:40",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057774,
        "FirstName": "Bret",
        "LastName": "Bolin",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 36,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Junior",
        "Height": 72,
        "Weight": 176,
        "BirthCity": "Lemont",
        "BirthState": "IL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-15T00:58:42",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057775,
        "FirstName": "C.J.",
        "LastName": "Williams",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 32,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 70,
        "Weight": 159,
        "BirthCity": "Gallion",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-15T00:59:06",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057776,
        "FirstName": "Shatarius",
        "LastName": "Williams",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 31,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 187,
        "BirthCity": "Demopolis",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-15T00:59:11",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057912,
        "FirstName": "Chase",
        "LastName": "Allen",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 82,
        "Position": "K",
        "PositionCategory": "ST",
        "Class": "Freshman",
        "Height": 74,
        "Weight": 188,
        "BirthCity": "Terryville",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:30:14",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057913,
        "FirstName": "Brian",
        "LastName": "Branch",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 14,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 190,
        "BirthCity": "Tyrone",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:30:17",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057914,
        "FirstName": "Jamil",
        "LastName": "Burroughs",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 98,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 326,
        "BirthCity": "Powder Springs",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:30:24",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057915,
        "FirstName": "Javion",
        "LastName": "Cohen",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 57,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 325,
        "BirthCity": "Phenix City",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:30:34",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057916,
        "FirstName": "Kyle",
        "LastName": "Flood Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 54,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 209,
        "BirthCity": "Middlesex",
        "BirthState": "NJ",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:30:42",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057917,
        "FirstName": "Damieon",
        "LastName": "George Jr.",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 74,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 78,
        "Weight": 345,
        "BirthCity": "Houston",
        "BirthState": "TX",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:31:00",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057918,
        "FirstName": "Clark",
        "LastName": "Griffin",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 24,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 69,
        "Weight": 195,
        "BirthCity": "Mountain Brook",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:31:03",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057919,
        "FirstName": "LT",
        "LastName": "Ikner",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 97,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Junior",
        "Height": 76,
        "Weight": 261,
        "BirthCity": "Daphne",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:31:06",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057920,
        "FirstName": "Sam",
        "LastName": "Johnson",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 98,
        "Position": "P",
        "PositionCategory": "ST",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 215,
        "BirthCity": "Birmingham",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:31:26",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057922,
        "FirstName": "Jah-Marien",
        "LastName": "Latham",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 93,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 285,
        "BirthCity": "Reform",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:31:39",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057924,
        "FirstName": "Malachi",
        "LastName": "Moore",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 13,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 182,
        "BirthCity": "Trussville",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:32:27",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057926,
        "FirstName": "Gavin",
        "LastName": "Reeder",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 91,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 292,
        "BirthCity": "Charlotte",
        "BirthState": "NC",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:33:36",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057927,
        "FirstName": "Quandarrius",
        "LastName": "Robinson",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 34,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 77,
        "Weight": 220,
        "BirthCity": "Birmingham",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:33:44",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057928,
        "FirstName": "Jordan",
        "LastName": "Smith",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 43,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 70,
        "Weight": 210,
        "BirthCity": "Chelsea",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:34:07",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057929,
        "FirstName": "Tim",
        "LastName": "Smith",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 50,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 320,
        "BirthCity": "Sebastian",
        "BirthState": "FL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:34:28",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057930,
        "FirstName": "Alajujuan",
        "LastName": "Sparks",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 68,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 76,
        "Weight": 345,
        "BirthCity": "Hoover",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:34:30",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50057931,
        "FirstName": "Kristian",
        "LastName": "Story",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 11,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 73,
        "Weight": 215,
        "BirthCity": "Lanett",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-09-18T13:34:35",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50059157,
        "FirstName": "Jonathan",
        "LastName": "Bennett",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 25,
        "Position": "WR",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 68,
        "Weight": 178,
        "BirthCity": "Birmingham",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-01T21:41:38",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50059182,
        "FirstName": "Robert",
        "LastName": "Ellis",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 51,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 220,
        "BirthCity": "Enterprise",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-01T21:45:51",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50059183,
        "FirstName": "Kyle",
        "LastName": "Mann",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 89,
        "Position": "DL",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 72,
        "Weight": 270,
        "BirthCity": "Powder Springs",
        "BirthState": "GA",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-01T21:48:59",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50059184,
        "FirstName": "Jacobi",
        "LastName": "McBride",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 25,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 73,
        "Weight": 143,
        "BirthCity": "Madison",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-01T21:50:45",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50059185,
        "FirstName": "Charlie",
        "LastName": "Skehan",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 56,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 73,
        "Weight": 232,
        "BirthCity": "Columbia",
        "BirthState": "SC",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-01T21:52:14",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50059186,
        "FirstName": "Bennett",
        "LastName": "Whisenhunt",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 59,
        "Position": "LB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 73,
        "Weight": 222,
        "BirthCity": "Vestavia",
        "BirthState": "AL",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-01T21:52:21",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50060602,
        "FirstName": "Sam",
        "LastName": "Willoughby",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 37,
        "Position": "DB",
        "PositionCategory": "DEF",
        "Class": "Freshman",
        "Height": 70,
        "Weight": 165,
        "BirthCity": null,
        "BirthState": null,
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-10-09T14:36:13",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50061531,
        "FirstName": "Donovan",
        "LastName": "Hardin",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 67,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": "Freshman",
        "Height": 75,
        "Weight": 285,
        "BirthCity": "Dublin",
        "BirthState": "OH",
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-11-03T15:38:27",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    },
    {
        "PlayerID": 50061690,
        "FirstName": "Brandon",
        "LastName": "Cade",
        "TeamID": 275,
        "Team": "ALA",
        "Jersey": 66,
        "Position": "OL",
        "PositionCategory": "OFF",
        "Class": null,
        "Height": 0,
        "Weight": 0,
        "BirthCity": null,
        "BirthState": null,
        "Updated": "2021-01-22T16:49:44",
        "Created": "2020-11-28T09:59:23",
        "GlobalTeamID": 50000275,
        "InjuryStatus": null,
        "InjuryBodyPart": null,
        "InjuryStartDate": null,
        "InjuryNotes": null
    }
]