module.exports.stadiaSeeds = [
  {
    StadiumID: 1,
    Active: true,
    Name: 'ANZ Stadium',
    Dome: false,
    City: 'Sydney',
    State: 'NSW',
    GeoLat: -33.847222,
    GeoLong: 151.063333,
  },
  {
    StadiumID: 2,
    Active: true,
    Name: 'Kelly/Shorts Stadium',
    Dome: false,
    City: 'Mount Pleasant',
    State: 'MI',
    GeoLat: 43.5775,
    GeoLong: -84.770833,
  },
  {
    StadiumID: 3,
    Active: true,
    Name: 'Truist Field at Wake Forest',
    Dome: false,
    City: 'Winston-Salem',
    State: 'NC',
    GeoLat: 36.130556,
    GeoLong: -80.254722,
  },
  {
    StadiumID: 4,
    Active: true,
    Name: 'Nippert Stadium',
    Dome: false,
    City: 'Cincinnati',
    State: 'OH',
    GeoLat: 39.131,
    GeoLong: -84.516,
  },
  {
    StadiumID: 5,
    Active: true,
    Name: 'Rentschler Field',
    Dome: false,
    City: 'East Hartford',
    State: 'CT',
    GeoLat: 41.759722,
    GeoLong: -72.618889,
  },
  {
    StadiumID: 6,
    Active: true,
    Name: 'Carter-Finley Stadium',
    Dome: false,
    City: 'Raleigh',
    State: 'NC',
    GeoLat: 35.800833,
    GeoLong: -78.719444,
  },
  {
    StadiumID: 7,
    Active: true,
    Name: 'Riccardo Silva Stadium',
    Dome: false,
    City: 'Miami',
    State: 'FL',
    GeoLat: 25.7525,
    GeoLong: -80.377778,
  },
  {
    StadiumID: 8,
    Active: true,
    Name: 'Neyland Stadium',
    Dome: false,
    City: 'Knoxville',
    State: 'TN',
    GeoLat: 0,
    GeoLong: 0,
  },
  {
    StadiumID: 9,
    Active: true,
    Name: 'Vanderbilt Stadium',
    Dome: false,
    City: 'Nashville',
    State: 'TN',
    GeoLat: 36.144167,
    GeoLong: -86.808889,
  },
  {
    StadiumID: 10,
    Active: true,
    Name: 'Rice-Eccles Stadium',
    Dome: false,
    City: 'Salt Lake City',
    State: 'UT',
    GeoLat: 40.76,
    GeoLong: -111.849,
  },
  {
    StadiumID: 11,
    Active: true,
    Name: 'Merlin Olsen Field At Maverik Stadium',
    Dome: false,
    City: 'Logan',
    State: 'UT',
    GeoLat: 41.751667,
    GeoLong: -111.811667,
  },
  {
    StadiumID: 12,
    Active: true,
    Name: 'L.T. Smith Stadium',
    Dome: false,
    City: 'Bowling Green',
    State: 'KY',
    GeoLat: 36.984722,
    GeoLong: -86.459444,
  },
  {
    StadiumID: 13,
    Active: true,
    Name: 'TCF Bank Stadium',
    Dome: false,
    City: 'Minneapolis',
    State: 'MN',
    GeoLat: 44.976,
    GeoLong: -93.225,
  },
  {
    StadiumID: 14,
    Active: true,
    Name: 'University Stadium',
    Dome: false,
    City: 'Albuquerque',
    State: 'NM',
    GeoLat: 35.066944,
    GeoLong: -106.628333,
  },
  {
    StadiumID: 15,
    Active: true,
    Name: 'Kibbie Dome',
    Dome: false,
    City: 'Moscow',
    State: 'ID',
    GeoLat: 46.726,
    GeoLong: -117.017,
  },
  {
    StadiumID: 16,
    Active: true,
    Name: 'Sam Boyd Stadium',
    Dome: false,
    City: 'Las Vegas',
    State: 'NV',
    GeoLat: 36.086,
    GeoLong: -115.017,
  },
  {
    StadiumID: 17,
    Active: true,
    Name: 'Rynearson Stadium',
    Dome: false,
    City: 'Ypsilanti',
    State: 'MI',
    GeoLat: 42.255833,
    GeoLong: -83.647222,
  },
  {
    StadiumID: 18,
    Active: true,
    Name: 'Georgia Dome',
    Dome: true,
    City: 'Atlanta',
    State: 'GA',
    GeoLat: 33.758,
    GeoLong: -84.401,
  },
  {
    StadiumID: 19,
    Active: true,
    Name: 'UB Stadium',
    Dome: false,
    City: 'Buffalo',
    State: 'NY',
    GeoLat: 42.999167,
    GeoLong: -78.7775,
  },
  {
    StadiumID: 20,
    Active: true,
    Name: 'Carrier Dome',
    Dome: true,
    City: 'Syracuse',
    State: 'NY',
    GeoLat: 43.036111,
    GeoLong: -76.136389,
  },
  {
    StadiumID: 21,
    Active: true,
    Name: 'Lincoln Financial Field',
    Dome: false,
    City: 'Philadelphia',
    State: 'PA',
    GeoLat: 39.900833,
    GeoLong: -75.1675,
  },
  {
    StadiumID: 22,
    Active: true,
    Name: 'Spartan Stadium (MI)',
    Dome: false,
    City: 'East Lansing',
    State: 'MI',
    GeoLat: 42.728056,
    GeoLong: -84.484722,
  },
  {
    StadiumID: 23,
    Active: true,
    Name: 'McLane Stadium',
    Dome: false,
    City: 'Waco',
    State: 'TX',
    GeoLat: 31.5582,
    GeoLong: -97.1157,
  },
  {
    StadiumID: 24,
    Active: true,
    Name: 'Stanford Stadium',
    Dome: false,
    City: 'Stanford',
    State: 'CA',
    GeoLat: 37.434444,
    GeoLong: -122.161111,
  },
  {
    StadiumID: 25,
    Active: true,
    Name: 'Centennial Bank Stadium',
    Dome: false,
    City: 'Jonesboro',
    State: 'AR',
    GeoLat: 35.848889,
    GeoLong: -90.667222,
  },
  {
    StadiumID: 26,
    Active: true,
    Name: 'Mackay Stadium',
    Dome: false,
    City: 'Reno',
    State: 'NV',
    GeoLat: 39.546944,
    GeoLong: -119.8175,
  },
  {
    StadiumID: 27,
    Active: true,
    Name: 'Aviva Stadium',
    Dome: false,
    City: 'Dublin',
    State: null,
    GeoLat: 53.335139,
    GeoLong: -6.228333,
  },
  {
    StadiumID: 28,
    Active: true,
    Name: 'NRG Stadium',
    Dome: true,
    City: 'Houston',
    State: 'TX',
    GeoLat: 29.684722,
    GeoLong: -95.410833,
  },
  {
    StadiumID: 29,
    Active: true,
    Name: 'Navy-Marine Corps Memorial Stadium',
    Dome: false,
    City: 'Annapolis',
    State: 'MD',
    GeoLat: 38.985,
    GeoLong: -76.507,
  },
  {
    StadiumID: 30,
    Active: true,
    Name: 'Ross-Ade Stadium',
    Dome: false,
    City: 'West Lafayette',
    State: 'IN',
    GeoLat: 40.434444,
    GeoLong: -86.918333,
  },
  {
    StadiumID: 31,
    Active: true,
    Name: 'Ohio Stadium',
    Dome: false,
    City: 'Columbus',
    State: 'OH',
    GeoLat: 40.001667,
    GeoLong: -83.019722,
  },
  {
    StadiumID: 32,
    Active: true,
    Name: 'Ryan Field',
    Dome: false,
    City: 'Evanston',
    State: 'IL',
    GeoLat: 42.065556,
    GeoLong: -87.6925,
  },
  {
    StadiumID: 33,
    Active: true,
    Name: 'Michigan Stadium',
    Dome: false,
    City: 'Ann Arbor',
    State: 'MI',
    GeoLat: 42.265833,
    GeoLong: -83.748611,
  },
  {
    StadiumID: 34,
    Active: true,
    Name: 'Cajun Field',
    Dome: false,
    City: 'Lafayette',
    State: 'LA',
    GeoLat: 30.215833,
    GeoLong: -92.041944,
  },
  {
    StadiumID: 35,
    Active: true,
    Name: 'Davis Wade Stadium',
    Dome: false,
    City: 'Starkville',
    State: 'MS',
    GeoLat: 33.456389,
    GeoLong: -88.793611,
  },
  {
    StadiumID: 36,
    Active: true,
    Name: 'Milan Puskar Stadium',
    Dome: false,
    City: 'Morgantown',
    State: 'WV',
    GeoLat: 39.650278,
    GeoLong: -79.954722,
  },
  {
    StadiumID: 37,
    Active: true,
    Name: 'Maryland Stadium',
    Dome: false,
    City: 'College Park',
    State: 'MD',
    GeoLat: 38.990278,
    GeoLong: -76.947222,
  },
  {
    StadiumID: 38,
    Active: true,
    Name: 'Lane Stadium',
    Dome: false,
    City: 'Blacksburg',
    State: 'VA',
    GeoLat: 37.22,
    GeoLong: -80.418056,
  },
  {
    StadiumID: 39,
    Active: true,
    Name: 'Heinz Field',
    Dome: false,
    City: 'Pittsburgh',
    State: 'PA',
    GeoLat: 40.446667,
    GeoLong: -80.015833,
  },
  {
    StadiumID: 40,
    Active: true,
    Name: 'Falcon Stadium',
    Dome: false,
    City: 'Usaf Academy',
    State: 'CO',
    GeoLat: 38.997,
    GeoLong: -104.843,
  },
  {
    StadiumID: 41,
    Active: true,
    Name: 'Husky Stadium',
    Dome: false,
    City: 'Seattle',
    State: 'WA',
    GeoLat: 47.650278,
    GeoLong: -122.301667,
  },
  {
    StadiumID: 42,
    Active: true,
    Name: 'Kyle Field',
    Dome: false,
    City: 'College Station',
    State: 'TX',
    GeoLat: 30.61,
    GeoLong: -96.340278,
  },
  {
    StadiumID: 43,
    Active: true,
    Name: 'Lambeau Field',
    Dome: false,
    City: 'Green Bay',
    State: 'WI',
    GeoLat: 44.501389,
    GeoLong: -88.062222,
  },
  {
    StadiumID: 44,
    Active: true,
    Name: 'Scott Stadium',
    Dome: false,
    City: 'Charlottesville',
    State: 'VA',
    GeoLat: 38.031111,
    GeoLong: -78.513611,
  },
  {
    StadiumID: 45,
    Active: true,
    Name: 'Kinnick Stadium',
    Dome: false,
    City: 'Iowa City',
    State: 'IA',
    GeoLat: 41.658611,
    GeoLong: -91.551111,
  },
  {
    StadiumID: 46,
    Active: true,
    Name: 'Peden Stadium',
    Dome: true,
    City: 'Athens',
    State: 'OH',
    GeoLat: 39.321111,
    GeoLong: -82.102778,
  },
  {
    StadiumID: 47,
    Active: true,
    Name: 'Memorial Stadium (Champaign, IL)',
    Dome: false,
    City: 'Champaign',
    State: 'IL',
    GeoLat: 40.099167,
    GeoLong: -88.235833,
  },
  {
    StadiumID: 48,
    Active: true,
    Name: 'Boone Pickens Stadium',
    Dome: false,
    City: 'Stillwater',
    State: 'OK',
    GeoLat: 36.125833,
    GeoLong: -97.066389,
  },
  {
    StadiumID: 49,
    Active: true,
    Name: 'Razorback Stadium',
    Dome: false,
    City: 'Fayetteville',
    State: 'AR',
    GeoLat: 36.068056,
    GeoLong: -94.178889,
  },
  {
    StadiumID: 50,
    Active: true,
    Name: 'Autzen Stadium',
    Dome: false,
    City: 'Eugene',
    State: 'OR',
    GeoLat: 44.058333,
    GeoLong: -123.068611,
  },
  {
    StadiumID: 51,
    Active: true,
    Name: 'FAU Stadium',
    Dome: false,
    City: 'Boca Raton',
    State: 'FL',
    GeoLat: 26.375278,
    GeoLong: -80.100278,
  },
  {
    StadiumID: 52,
    Active: true,
    Name: 'S.B. Ballard Stadium',
    Dome: false,
    City: 'Norfolk',
    State: 'VA',
    GeoLat: 36.8889,
    GeoLong: -76.304878,
  },
  {
    StadiumID: 53,
    Active: true,
    Name: 'Wallace Wade Stadium',
    Dome: false,
    City: 'Durham',
    State: 'NC',
    GeoLat: 35.995278,
    GeoLong: -78.941667,
  },
  {
    StadiumID: 54,
    Active: true,
    Name: 'Dowdy-Ficklen Stadium',
    Dome: false,
    City: 'Greenville',
    State: 'NC',
    GeoLat: 35.596389,
    GeoLong: -77.365278,
  },
  {
    StadiumID: 55,
    Active: true,
    Name: 'Hard Rock Stadium',
    Dome: false,
    City: 'Miami Gardens',
    State: 'FL',
    GeoLat: 25.958056,
    GeoLong: -80.238889,
  },
  {
    StadiumID: 56,
    Active: true,
    Name: 'Allen E. Paulson Stadium',
    Dome: false,
    City: 'Statesboro',
    State: 'GA',
    GeoLat: 32.412161,
    GeoLong: -81.783135,
  },
  {
    StadiumID: 57,
    Active: true,
    Name: 'Veterans Memorial Stadium (AL)',
    Dome: true,
    City: 'Troy',
    State: 'AL',
    GeoLat: 33.469444,
    GeoLong: -112.096667,
  },
  {
    StadiumID: 58,
    Active: true,
    Name: 'InfoCision Stadium',
    Dome: false,
    City: 'Akron',
    State: 'OH',
    GeoLat: 41.072347,
    GeoLong: -81.508019,
  },
  {
    StadiumID: 59,
    Active: true,
    Name: 'Floyd Stadium',
    Dome: false,
    City: 'Murfreesboro',
    State: 'TN',
    GeoLat: 35.850513,
    GeoLong: -86.368223,
  },
  {
    StadiumID: 60,
    Active: true,
    Name: 'Apogee Stadium',
    Dome: false,
    City: 'Denton',
    State: 'TX',
    GeoLat: 33.203611,
    GeoLong: -97.159444,
  },
  {
    StadiumID: 61,
    Active: true,
    Name: 'Chapman Stadium',
    Dome: false,
    City: 'Tulsa',
    State: 'OK',
    GeoLat: 36.148611,
    GeoLong: -95.943889,
  },
  {
    StadiumID: 62,
    Active: true,
    Name: 'Raymond James Stadium',
    Dome: false,
    City: 'Tampa',
    State: 'FL',
    GeoLat: 27.975833,
    GeoLong: -82.503333,
  },
  {
    StadiumID: 63,
    Active: true,
    Name: 'Bounce House',
    Dome: false,
    City: 'Orlando',
    State: 'FL',
    GeoLat: 28.6091,
    GeoLong: -81.1924,
  },
  {
    StadiumID: 64,
    Active: true,
    Name: 'Memorial Stadium (Lawrence, KS)',
    Dome: false,
    City: 'Lawrence',
    State: 'KS',
    GeoLat: 38.879722,
    GeoLong: -95.313056,
  },
  {
    StadiumID: 65,
    Active: true,
    Name: 'Liberty Bowl Memorial Stadium',
    Dome: false,
    City: 'Memphis',
    State: 'TN',
    GeoLat: 35.121111,
    GeoLong: -89.9775,
  },
  {
    StadiumID: 66,
    Active: true,
    Name: 'Alamodome',
    Dome: true,
    City: 'San Antonio',
    State: 'TX',
    GeoLat: 29.416944,
    GeoLong: -98.478889,
  },
  {
    StadiumID: 67,
    Active: true,
    Name: 'Malone Stadium',
    Dome: false,
    City: 'Monroe',
    State: 'LA',
    GeoLat: 32.530833,
    GeoLong: -92.065833,
  },
  {
    StadiumID: 68,
    Active: true,
    Name: 'Kroger Field',
    Dome: false,
    City: 'Lexington',
    State: 'KY',
    GeoLat: 38.022778,
    GeoLong: -84.505278,
  },
  {
    StadiumID: 69,
    Active: true,
    Name: 'Ben Hill Griffin Stadium',
    Dome: false,
    City: 'Gainesville',
    State: 'FL',
    GeoLat: 29.65,
    GeoLong: -82.348611,
  },
  {
    StadiumID: 70,
    Active: true,
    Name: 'AT&T Stadium',
    Dome: false,
    City: 'Arlington',
    State: 'TX',
    GeoLat: 32.747778,
    GeoLong: -97.092778,
  },
  {
    StadiumID: 71,
    Active: true,
    Name: 'Jack Trice Stadium',
    Dome: false,
    City: 'Ames',
    State: 'IA',
    GeoLat: 42.014167,
    GeoLong: -93.635833,
  },
  {
    StadiumID: 72,
    Active: true,
    Name: 'Memorial Stadium (Lincoln, NE)',
    Dome: false,
    City: 'Lincoln',
    State: 'NE',
    GeoLat: 40.820556,
    GeoLong: -96.705556,
  },
  {
    StadiumID: 73,
    Active: true,
    Name: 'Martin Stadium',
    Dome: false,
    City: 'Pullman',
    State: 'WA',
    GeoLat: 46.732,
    GeoLong: -117.16,
  },
  {
    StadiumID: 74,
    Active: true,
    Name: 'Sun Bowl',
    Dome: false,
    City: 'El Paso',
    State: 'TX',
    GeoLat: 31.773,
    GeoLong: -106.508,
  },
  {
    StadiumID: 75,
    Active: true,
    Name: 'Amon G. Carter Stadium',
    Dome: false,
    City: 'Fort Worth',
    State: 'TX',
    GeoLat: 32.709722,
    GeoLong: -97.368056,
  },
  {
    StadiumID: 76,
    Active: true,
    Name: 'Jones AT&T Stadium',
    Dome: false,
    City: 'Lubbock',
    State: 'TX',
    GeoLat: 33.591111,
    GeoLong: -101.872778,
  },
  {
    StadiumID: 77,
    Active: true,
    Name: 'SDCCU Stadium',
    Dome: false,
    City: 'San Diego',
    State: 'CA',
    GeoLat: 32.783056,
    GeoLong: -117.119444,
  },
  {
    StadiumID: 78,
    Active: true,
    Name: 'Jordan-Hare Stadium',
    Dome: false,
    City: 'Auburn',
    State: 'AL',
    GeoLat: 32.602222,
    GeoLong: -85.489167,
  },
  {
    StadiumID: 79,
    Active: true,
    Name: 'State Farm Stadium',
    Dome: true,
    City: 'Glendale',
    State: 'AZ',
    GeoLat: 33.528,
    GeoLong: -112.263,
  },
  {
    StadiumID: 80,
    Active: true,
    Name: 'War Memorial Stadium (WY)',
    Dome: false,
    City: 'Laramie',
    State: 'WY',
    GeoLat: 41.312,
    GeoLong: -105.568,
  },
  {
    StadiumID: 81,
    Active: true,
    Name: 'Sun Devil Stadium',
    Dome: false,
    City: 'Tempe',
    State: 'AZ',
    GeoLat: 33.426389,
    GeoLong: -111.9325,
  },
  {
    StadiumID: 82,
    Active: true,
    Name: 'Royal Texas Memorial Stadium',
    Dome: false,
    City: 'Austin',
    State: 'TX',
    GeoLat: 30.283611,
    GeoLong: -97.7325,
  },
  {
    StadiumID: 83,
    Active: true,
    Name: 'Camping World Stadium',
    Dome: false,
    City: 'Orlando',
    State: 'FL',
    GeoLat: 28.538889,
    GeoLong: -81.402778,
  },
  {
    StadiumID: 84,
    Active: true,
    Name: 'TDECU Stadium',
    Dome: false,
    City: 'Houston',
    State: 'TX',
    GeoLat: 29.721944,
    GeoLong: -95.349167,
  },
  {
    StadiumID: 85,
    Active: true,
    Name: 'High Point Solutions Stadium',
    Dome: false,
    City: 'Piscataway',
    State: 'NJ',
    GeoLat: 40.513611,
    GeoLong: -74.465278,
  },
  {
    StadiumID: 86,
    Active: true,
    Name: 'Michie Stadium',
    Dome: false,
    City: 'West Point',
    State: 'NY',
    GeoLat: 41.3875,
    GeoLong: -73.964167,
  },
  {
    StadiumID: 87,
    Active: true,
    Name: 'Gillette Stadium',
    Dome: false,
    City: 'Foxboro',
    State: 'MA',
    GeoLat: 42.091,
    GeoLong: -71.264,
  },
  {
    StadiumID: 88,
    Active: true,
    Name: 'Sanford Stadium',
    Dome: false,
    City: 'Athens',
    State: 'GA',
    GeoLat: 33.949722,
    GeoLong: -83.373333,
  },
  {
    StadiumID: 89,
    Active: true,
    Name: 'Doak Campbell Stadium',
    Dome: false,
    City: 'Tallahassee',
    State: 'FL',
    GeoLat: 30.438056,
    GeoLong: -84.304444,
  },
  {
    StadiumID: 90,
    Active: true,
    Name: 'Memorial Stadium (Clemson, SC)',
    Dome: false,
    City: 'Clemson',
    State: 'SC',
    GeoLat: 34.678611,
    GeoLong: -82.843056,
  },
  {
    StadiumID: 91,
    Active: true,
    Name: 'Los Angeles Memorial Coliseum',
    Dome: false,
    City: 'Los Angeles',
    State: 'CA',
    GeoLat: 34.014167,
    GeoLong: -118.287778,
  },
  {
    StadiumID: 92,
    Active: true,
    Name: 'Bobby Dodd Stadium',
    Dome: false,
    City: 'Atlanta',
    State: 'GA',
    GeoLat: 33.7725,
    GeoLong: -84.392778,
  },
  {
    StadiumID: 93,
    Active: true,
    Name: 'Doyt Perry Stadium',
    Dome: false,
    City: 'Bowling Green',
    State: 'OH',
    GeoLat: 41.378056,
    GeoLong: -83.6225,
  },
  {
    StadiumID: 94,
    Active: true,
    Name: 'Yager Stadium',
    Dome: false,
    City: 'Oxford',
    State: 'OH',
    GeoLat: 39.519444,
    GeoLong: -84.732778,
  },
  {
    StadiumID: 95,
    Active: true,
    Name: 'Kidd Brewer Stadium',
    Dome: false,
    City: 'Boone',
    State: 'NC',
    GeoLat: 36.211667,
    GeoLong: -81.685556,
  },
  {
    StadiumID: 96,
    Active: true,
    Name: 'Camp Randall Stadium',
    Dome: false,
    City: 'Madison',
    State: 'WI',
    GeoLat: 43.07,
    GeoLong: -89.412778,
  },
  {
    StadiumID: 97,
    Active: true,
    Name: 'Notre Dame Stadium',
    Dome: false,
    City: 'Notre Dame',
    State: 'IN',
    GeoLat: 41.698,
    GeoLong: -86.234,
  },
  {
    StadiumID: 98,
    Active: true,
    Name: 'Bryant-Denny Stadium',
    Dome: false,
    City: 'Tuscaloosa',
    State: 'AL',
    GeoLat: 33.207778,
    GeoLong: -87.550556,
  },
  {
    StadiumID: 99,
    Active: true,
    Name: 'Vaught-Hemingway Stadium',
    Dome: false,
    City: 'Oxford',
    State: 'MS',
    GeoLat: 34.361944,
    GeoLong: -89.534167,
  },
  {
    StadiumID: 100,
    Active: true,
    Name: 'Memorial Stadium (Bloomington, IN)',
    Dome: false,
    City: 'Bloomington',
    State: 'IN',
    GeoLat: 39.180833,
    GeoLong: -86.525556,
  },
  {
    StadiumID: 101,
    Active: true,
    Name: 'CEFCU Stadium',
    Dome: false,
    City: 'San Jose',
    State: 'CA',
    GeoLat: 37.319722,
    GeoLong: -121.868333,
  },
  {
    StadiumID: 102,
    Active: true,
    Name: 'Folsom Field',
    Dome: false,
    City: 'Boulder',
    State: 'CO',
    GeoLat: 40.009,
    GeoLong: -105.267,
  },
  {
    StadiumID: 103,
    Active: true,
    Name: 'Joan C. Edwards Stadium',
    Dome: false,
    City: 'Huntington',
    State: 'WV',
    GeoLat: 38.425,
    GeoLong: -82.420833,
  },
  {
    StadiumID: 104,
    Active: true,
    Name: 'Ladd-Peebles Stadium',
    Dome: false,
    City: 'Mobile',
    State: 'AL',
    GeoLat: 30.673,
    GeoLong: -88.076,
  },
  {
    StadiumID: 105,
    Active: true,
    Name: 'Memorial Stadium (Norman, OK)',
    Dome: false,
    City: 'Norman',
    State: 'OK',
    GeoLat: 35.205833,
    GeoLong: -97.4425,
  },
  {
    StadiumID: 106,
    Active: true,
    Name: 'Waldo Stadium',
    Dome: false,
    City: 'Kalamazoo',
    State: 'MI',
    GeoLat: 42.285833,
    GeoLong: -85.601111,
  },
  {
    StadiumID: 107,
    Active: true,
    Name: 'Glass Bowl',
    Dome: false,
    City: 'Toledo',
    State: 'OH',
    GeoLat: 41.656944,
    GeoLong: -83.613611,
  },
  {
    StadiumID: 108,
    Active: true,
    Name: 'Joe Aillet Stadium',
    Dome: false,
    City: 'Ruston',
    State: 'LA',
    GeoLat: 32.532222,
    GeoLong: -92.655833,
  },
  {
    StadiumID: 109,
    Active: true,
    Name: 'M.M. Roberts Stadium',
    Dome: false,
    City: 'Hattiesburg',
    State: 'MS',
    GeoLat: 31.328889,
    GeoLong: -89.331389,
  },
  {
    StadiumID: 110,
    Active: true,
    Name: 'Faurot Field at Memorial Stadium',
    Dome: false,
    City: 'Columbia',
    State: 'MO',
    GeoLat: 38.935833,
    GeoLong: -92.333056,
  },
  {
    StadiumID: 111,
    Active: true,
    Name: 'Tiger Stadium (LA)',
    Dome: false,
    City: 'Baton Rouge',
    State: 'LA',
    GeoLat: 30.411944,
    GeoLong: -91.185556,
  },
  {
    StadiumID: 112,
    Active: true,
    Name: 'Yulman Stadium',
    Dome: false,
    City: 'New Orleans',
    State: 'LA',
    GeoLat: 29.94482,
    GeoLong: -90.116816,
  },
  {
    StadiumID: 113,
    Active: true,
    Name: 'Bristol Motor Speedway',
    Dome: false,
    City: 'Bristol',
    State: 'TN',
    GeoLat: 36.5156,
    GeoLong: -82.2569,
  },
  {
    StadiumID: 114,
    Active: true,
    Name: 'Rose Bowl',
    Dome: false,
    City: 'Pasadena',
    State: 'CA',
    GeoLat: 34.161,
    GeoLong: -118.168,
  },
  {
    StadiumID: 115,
    Active: true,
    Name: 'Aggie Memorial Stadium',
    Dome: false,
    City: 'Las Cruces',
    State: 'NM',
    GeoLat: 32.279722,
    GeoLong: -106.741111,
  },
  {
    StadiumID: 116,
    Active: true,
    Name: 'Bulldog Stadium (CA)',
    Dome: false,
    City: 'Fresno',
    State: 'CA',
    GeoLat: 36.814,
    GeoLong: -119.758,
  },
  {
    StadiumID: 117,
    Active: true,
    Name: 'Albertsons Stadium',
    Dome: false,
    City: 'Boise',
    State: 'ID',
    GeoLat: 43.603,
    GeoLong: -116.196,
  },
  {
    StadiumID: 118,
    Active: true,
    Name: 'Arizona Stadium',
    Dome: false,
    City: 'Tucson',
    State: 'AZ',
    GeoLat: 32.229,
    GeoLong: -110.949,
  },
  {
    StadiumID: 119,
    Active: true,
    Name: 'Aloha Stadium',
    Dome: false,
    City: 'Honolulu',
    State: 'HI',
    GeoLat: 21.373,
    GeoLong: -157.93,
  },
  {
    StadiumID: 120,
    Active: true,
    Name: 'Rice Stadium',
    Dome: false,
    City: 'Houston',
    State: 'TX',
    GeoLat: 29.716389,
    GeoLong: -95.409167,
  },
  {
    StadiumID: 121,
    Active: true,
    Name: 'Cardinal Stadium',
    Dome: false,
    City: 'Louisville',
    State: 'KY',
    GeoLat: 38.205833,
    GeoLong: -85.758889,
  },
  {
    StadiumID: 122,
    Active: true,
    Name: 'Beaver Stadium',
    Dome: false,
    City: 'University Park',
    State: 'PA',
    GeoLat: 40.812222,
    GeoLong: -77.856111,
  },
  {
    StadiumID: 123,
    Active: true,
    Name: 'Bill Snyder Family Stadium',
    Dome: false,
    City: 'Manhattan',
    State: 'KS',
    GeoLat: 39.201944,
    GeoLong: -96.593889,
  },
  {
    StadiumID: 124,
    Active: true,
    Name: 'Scheumann Stadium',
    Dome: false,
    City: 'Muncie',
    State: 'IN',
    GeoLat: 40.216111,
    GeoLong: -85.416667,
  },
  {
    StadiumID: 125,
    Active: true,
    Name: 'Huskie Stadium',
    Dome: false,
    City: 'DeKalb',
    State: 'IL',
    GeoLat: 41.934,
    GeoLong: -88.778,
  },
  {
    StadiumID: 126,
    Active: true,
    Name: 'Warren McGuirk Alumni Stadium',
    Dome: false,
    City: 'Amherst',
    State: 'MA',
    GeoLat: 42.377306,
    GeoLong: -72.536019,
  },
  {
    StadiumID: 127,
    Active: true,
    Name: 'Kenan Stadium',
    Dome: false,
    City: 'Chapel Hill',
    State: 'NC',
    GeoLat: 35.906944,
    GeoLong: -79.047778,
  },
  {
    StadiumID: 128,
    Active: true,
    Name: 'Williams-Brice Stadium',
    Dome: false,
    City: 'Columbia',
    State: 'SC',
    GeoLat: 33.973056,
    GeoLong: -81.019167,
  },
  {
    StadiumID: 129,
    Active: true,
    Name: 'Reser Stadium',
    Dome: false,
    City: 'Corvallis',
    State: 'OR',
    GeoLat: 44.559,
    GeoLong: -123.281,
  },
  {
    StadiumID: 130,
    Active: true,
    Name: 'Gerald J. Ford Stadium',
    Dome: false,
    City: 'Dallas',
    State: 'TX',
    GeoLat: 32.836644,
    GeoLong: -96.783994,
  },
  {
    StadiumID: 131,
    Active: true,
    Name: 'LaVell Edwards Stadium',
    Dome: false,
    City: 'Provo',
    State: 'UT',
    GeoLat: 40.258,
    GeoLong: -111.655,
  },
  {
    StadiumID: 132,
    Active: true,
    Name: 'California Memorial Stadium',
    Dome: false,
    City: 'Berkeley',
    State: 'CA',
    GeoLat: 37.871111,
    GeoLong: -122.250833,
  },
  {
    StadiumID: 133,
    Active: true,
    Name: 'FedExField',
    Dome: false,
    City: 'Landover',
    State: 'MD',
    GeoLat: 38.907778,
    GeoLong: -76.864444,
  },
  {
    StadiumID: 134,
    Active: true,
    Name: 'Alumni Stadium (MA)',
    Dome: false,
    City: 'Chestnut Hill',
    State: 'MA',
    GeoLat: 42.335,
    GeoLong: -71.166389,
  },
  {
    StadiumID: 135,
    Active: true,
    Name: 'Bobcat Stadium (TX)',
    Dome: false,
    City: 'San Marcos',
    State: 'TX',
    GeoLat: 29.891111,
    GeoLong: -97.925556,
  },
  {
    StadiumID: 136,
    Active: true,
    Name: 'MetLife Stadium',
    Dome: false,
    City: 'East Rutherford',
    State: 'NJ',
    GeoLat: 40.813528,
    GeoLong: -74.074361,
  },
  {
    StadiumID: 137,
    Active: true,
    Name: 'War Memorial Stadium (AR)',
    Dome: false,
    City: 'Little Rock',
    State: 'AR',
    GeoLat: 34.749861,
    GeoLong: -92.33,
  },
  {
    StadiumID: 138,
    Active: true,
    Name: 'Cotton Bowl',
    Dome: false,
    City: 'Dallas',
    State: 'TX',
    GeoLat: 32.779722,
    GeoLong: -96.759722,
  },
  {
    StadiumID: 139,
    Active: true,
    Name: 'TIAA Bank Field',
    Dome: false,
    City: 'Jacksonville',
    State: 'FL',
    GeoLat: 30.323889,
    GeoLong: -81.6375,
  },
  {
    StadiumID: 140,
    Active: true,
    Name: 'Guaranteed Rate Field',
    Dome: false,
    City: 'Chicago',
    State: 'IL',
    GeoLat: 41.83,
    GeoLong: -87.633889,
  },
  {
    StadiumID: 141,
    Active: true,
    Name: 'Nissan Stadium',
    Dome: false,
    City: 'Nashville',
    State: 'TN',
    GeoLat: 36.166389,
    GeoLong: -86.771389,
  },
  {
    StadiumID: 142,
    Active: true,
    Name: 'Fenway Park',
    Dome: false,
    City: 'Boston',
    State: 'MA',
    GeoLat: 42.34625,
    GeoLong: -71.09775,
  },
  {
    StadiumID: 143,
    Active: true,
    Name: 'Soldier Field',
    Dome: false,
    City: 'Chicago',
    State: 'IL',
    GeoLat: 41.8623,
    GeoLong: -87.6167,
  },
  {
    StadiumID: 144,
    Active: true,
    Name: 'Bank of America Stadium',
    Dome: false,
    City: 'Charlotte',
    State: 'NC',
    GeoLat: 35.225833,
    GeoLong: -80.852778,
  },
  {
    StadiumID: 145,
    Active: true,
    Name: 'Lucas Oil Stadium',
    Dome: true,
    City: 'Indianapolis',
    State: 'IN',
    GeoLat: 39.760056,
    GeoLong: -86.163806,
  },
  {
    StadiumID: 146,
    Active: true,
    Name: 'Levis Stadium',
    Dome: false,
    City: 'Santa Clara',
    State: 'CA',
    GeoLat: 37.403,
    GeoLong: -121.97,
  },
  {
    StadiumID: 147,
    Active: true,
    Name: 'Cramton Bowl',
    Dome: false,
    City: 'Montgomery',
    State: 'AL',
    GeoLat: 32.37949,
    GeoLong: -86.293002,
  },
  {
    StadiumID: 148,
    Active: true,
    Name: 'Mercedes-Benz Superdome',
    Dome: false,
    City: 'New Orleans',
    State: 'LA',
    GeoLat: 29.950833,
    GeoLong: -90.081111,
  },
  {
    StadiumID: 149,
    Active: true,
    Name: 'MARLINS PARK',
    Dome: true,
    City: 'Miami',
    State: 'FL',
    GeoLat: 25.778056,
    GeoLong: -80.219722,
  },
  {
    StadiumID: 150,
    Active: true,
    Name: 'Thomas Robinson Stadium',
    Dome: false,
    City: 'Nassau',
    State: 'NP',
    GeoLat: 25.054381,
    GeoLong: -77.360217,
  },
  {
    StadiumID: 151,
    Active: true,
    Name: 'Tropicana Field',
    Dome: true,
    City: 'Saint Petersburg',
    State: 'FL',
    GeoLat: 27.768333,
    GeoLong: -82.653333,
  },
  {
    StadiumID: 152,
    Active: true,
    Name: 'Yankee Stadium',
    Dome: false,
    City: 'New York',
    State: 'NY',
    GeoLat: 40.829167,
    GeoLong: -73.926389,
  },
  {
    StadiumID: 153,
    Active: true,
    Name: 'Independence Stadium',
    Dome: false,
    City: 'Shreveport',
    State: 'LA',
    GeoLat: 32.475556,
    GeoLong: -93.791944,
  },
  {
    StadiumID: 154,
    Active: true,
    Name: 'Ford Field',
    Dome: true,
    City: 'Detroit',
    State: 'MI',
    GeoLat: 42.34,
    GeoLong: -83.045556,
  },
  {
    StadiumID: 155,
    Active: true,
    Name: 'Legion Field (AL)',
    Dome: false,
    City: 'Birmingham',
    State: 'AL',
    GeoLat: 33.511389,
    GeoLong: -86.842778,
  },
  {
    StadiumID: 156,
    Active: true,
    Name: 'Chase Field',
    Dome: true,
    City: 'Phoenix',
    State: 'AZ',
    GeoLat: 33.445278,
    GeoLong: -112.066944,
  },
  {
    StadiumID: 157,
    Active: true,
    Name: 'M&T Bank Stadium',
    Dome: false,
    City: 'Baltimore',
    State: 'MD',
    GeoLat: 39.278056,
    GeoLong: -76.622778,
  },
  {
    StadiumID: 158,
    Active: true,
    Name: 'Sports Authority Field',
    Dome: false,
    City: 'Denver',
    State: 'CO',
    GeoLat: 39.743889,
    GeoLong: -105.02,
  },
  {
    StadiumID: 159,
    Active: true,
    Name: 'Hughes Stadium (CO)',
    Dome: false,
    City: 'Fort Collins',
    State: 'CO',
    GeoLat: 40.562,
    GeoLong: -105.142,
  },
  {
    StadiumID: 160,
    Active: true,
    Name: 'Dix Stadium',
    Dome: false,
    City: 'Kent',
    State: 'OH',
    GeoLat: 41.139167,
    GeoLong: -81.313333,
  },
  {
    StadiumID: 161,
    Active: true,
    Name: 'McColl-Richardson Field',
    Dome: false,
    City: 'Charlotte',
    State: 'NC',
    GeoLat: 35.310556,
    GeoLong: -80.740278,
  },
  {
    StadiumID: 162,
    Active: true,
    Name: 'Arrowhead Stadium',
    Dome: false,
    City: 'Kansas City',
    State: 'MO',
    GeoLat: 39.048889,
    GeoLong: -94.483889,
  },
  {
    StadiumID: 163,
    Active: true,
    Name: 'Mercedes-Benz Stadium',
    Dome: true,
    City: 'Atlanta',
    State: 'GA',
    GeoLat: 33.755556,
    GeoLong: -84.4,
  },
  {
    StadiumID: 164,
    Active: true,
    Name: 'Allianz Stadium',
    Dome: false,
    City: 'Sydney',
    State: 'NSW',
    GeoLat: -33.889167,
    GeoLong: 151.225278,
  },
  {
    StadiumID: 165,
    Active: true,
    Name: 'CSU Stadium',
    Dome: false,
    City: 'Fort Collins',
    State: 'CO',
    GeoLat: 40.57,
    GeoLong: -105.0885,
  },
  {
    StadiumID: 166,
    Active: true,
    Name: 'Georgia State Stadium',
    Dome: false,
    City: 'Atlanta',
    State: 'GA',
    GeoLat: 33.735278,
    GeoLong: -84.389444,
  },
  {
    StadiumID: 167,
    Active: true,
    Name: 'Brooks Stadium',
    Dome: false,
    City: 'Conway',
    State: 'SC',
    GeoLat: 33.793013,
    GeoLong: -79.017652,
  },
  {
    StadiumID: 168,
    Active: true,
    Name: 'Floyd Casey Stadium',
    Dome: false,
    City: 'Waco',
    State: 'TX',
    GeoLat: 31.531342,
    GeoLong: -97.148731,
  },
  {
    StadiumID: 169,
    Active: true,
    Name: 'Robertson Stadium',
    Dome: false,
    City: 'Houston',
    State: 'TX',
    GeoLat: 29.721944,
    GeoLong: -95.349167,
  },
  {
    StadiumID: 170,
    Active: true,
    Name: 'Roy Kidd Stadium',
    Dome: false,
    City: 'Richmond',
    State: 'KY',
    GeoLat: 37.73439,
    GeoLong: -84.29741,
  },
  {
    StadiumID: 171,
    Active: true,
    Name: 'Superior Dome',
    Dome: false,
    City: 'Marquette',
    State: 'MI',
    GeoLat: 46.56,
    GeoLong: -87.393611,
  },
  {
    StadiumID: 172,
    Active: true,
    Name: 'William Price Stadium',
    Dome: false,
    City: 'Norfolk',
    State: 'VA',
    GeoLat: 36.846964,
    GeoLong: -76.260053,
  },
  {
    StadiumID: 173,
    Active: true,
    Name: 'Croke Park Stadium',
    Dome: false,
    City: 'Dublin',
    State: null,
    GeoLat: 53.36075,
    GeoLong: -6.251333,
  },
  {
    StadiumID: 174,
    Active: true,
    Name: 'Lumen Field',
    Dome: false,
    City: 'Seattle',
    State: 'WA',
    GeoLat: 47.5952,
    GeoLong: -122.3316,
  },
  {
    StadiumID: 175,
    Active: true,
    Name: 'Paul Brown Stadium',
    Dome: false,
    City: 'Cincinnati',
    State: 'OH',
    GeoLat: 39.095,
    GeoLong: -84.516,
  },
  {
    StadiumID: 176,
    Active: true,
    Name: 'Yale Bowl',
    Dome: false,
    City: 'New Haven',
    State: 'CT',
    GeoLat: 41.313,
    GeoLong: -72.96,
  },
  {
    StadiumID: 177,
    Active: true,
    Name: 'Dana J. Dykhouse Stadium',
    Dome: false,
    City: 'Brookings',
    State: 'SD',
    GeoLat: 44.321026,
    GeoLong: -96.780144,
  },
  {
    StadiumID: 178,
    Active: true,
    Name: 'Toyota Stadium',
    Dome: false,
    City: 'Frisco',
    State: 'TX',
    GeoLat: 33.154444,
    GeoLong: -96.835278,
  },
  {
    StadiumID: 179,
    Active: true,
    Name: 'Williams Stadium (VA)',
    Dome: false,
    City: 'Lynchburg',
    State: 'VA',
    GeoLat: 37.354,
    GeoLong: -79.175,
  },
  {
    StadiumID: 180,
    Active: true,
    Name: 'Holt Arena',
    Dome: false,
    City: 'Pocatello',
    State: 'ID',
    GeoLat: 42.87,
    GeoLong: -112.429,
  },
  {
    StadiumID: 181,
    Active: true,
    Name: 'Bobcat Stadium (MT)',
    Dome: false,
    City: 'Bozeman',
    State: 'MT',
    GeoLat: 45.659,
    GeoLong: -111.049,
  },
  {
    StadiumID: 182,
    Active: true,
    Name: 'Roos Field',
    Dome: false,
    City: 'Cheney',
    State: 'WA',
    GeoLat: 47.493,
    GeoLong: -117.588,
  },
  {
    StadiumID: 183,
    Active: true,
    Name: 'Alerus Center',
    Dome: true,
    City: 'Grand Forks',
    State: 'ND',
    GeoLat: 47.916111,
    GeoLong: -97.090833,
  },
  {
    StadiumID: 184,
    Active: true,
    Name: 'Aggie Stadium (UC Davis)',
    Dome: false,
    City: 'Davis',
    State: 'CA',
    GeoLat: 38.536506,
    GeoLong: -121.762778,
  },
  {
    StadiumID: 185,
    Active: true,
    Name: 'T.A. Wright Stadium',
    Dome: false,
    City: 'Savannah',
    State: 'GA',
    GeoLat: 32.027593,
    GeoLong: -81.068673,
  },
  {
    StadiumID: 186,
    Active: true,
    Name: 'Rice-Totten Stadium',
    Dome: false,
    City: 'Itta Bena',
    State: 'MS',
    GeoLat: 33.509444,
    GeoLong: -90.343056,
  },
  {
    StadiumID: 187,
    Active: true,
    Name: 'Barker-Lane Stadium',
    Dome: false,
    City: 'Buies Creek',
    State: 'NC',
    GeoLat: 35.4046,
    GeoLong: -78.7427,
  },
  {
    StadiumID: 188,
    Active: true,
    Name: 'Andy Kerr Stadium',
    Dome: false,
    City: 'Hamilton',
    State: 'NY',
    GeoLat: 42.816944,
    GeoLong: -75.5452,
  },
  {
    StadiumID: 189,
    Active: true,
    Name: 'Fargodome',
    Dome: false,
    City: 'Fargo',
    State: 'ND',
    GeoLat: 46.903036,
    GeoLong: -96.80155,
  },
  {
    StadiumID: 190,
    Active: true,
    Name: 'Jack Spinks Stadium',
    Dome: false,
    City: 'Alcorn State',
    State: 'MS',
    GeoLat: 31.873545,
    GeoLong: -91.134918,
  },
  {
    StadiumID: 191,
    Active: true,
    Name: 'Morse Field At Harold Alfond Stadium',
    Dome: false,
    City: 'Orono',
    State: 'ME',
    GeoLat: 44.905,
    GeoLong: -68.671667,
  },
  {
    StadiumID: 193,
    Active: true,
    Name: 'Exploria Stadium',
    Dome: false,
    City: 'Orlando',
    State: 'FL',
    GeoLat: 28.5411,
    GeoLong: -81.3893,
  },
  {
    StadiumID: 194,
    Active: true,
    Name: 'Wrigley Field',
    Dome: false,
    City: 'Chicago',
    State: 'IL',
    GeoLat: 41.948056,
    GeoLong: -87.655556,
  },
  {
    StadiumID: 195,
    Active: true,
    Name: 'Allegiant Stadium',
    Dome: false,
    City: 'Las Vegas',
    State: 'NV',
    GeoLat: 36.090833,
    GeoLong: -115.183611,
  },
  {
    StadiumID: 196,
    Active: true,
    Name: 'SeatGeek Stadium',
    Dome: false,
    City: 'Bridgeview',
    State: 'IL',
    GeoLat: 41.764722,
    GeoLong: -87.806111,
  },
  {
    StadiumID: 197,
    Active: true,
    Name: 'Hancock Whitney Stadium',
    Dome: false,
    City: 'Mobile',
    State: 'AL',
    GeoLat: 30.696904,
    GeoLong: -88.192013,
  },
  {
    StadiumID: 198,
    Active: true,
    Name: 'Convoy Leslie Cotton Boll Stadium',
    Dome: false,
    City: 'Monticello',
    State: 'AR',
    GeoLat: 33.59208,
    GeoLong: -91.81158,
  },
  {
    StadiumID: 199,
    Active: true,
    Name: 'Duvall-Rosier Field',
    Dome: false,
    City: 'Fairmont',
    State: 'WV',
    GeoLat: 39.48576,
    GeoLong: -80.16119,
  },
  {
    StadiumID: 200,
    Active: true,
    Name: 'Knight Stadium',
    Dome: false,
    City: 'Buena Vista',
    State: 'VA',
    GeoLat: 37.742222,
    GeoLong: -79.338611,
  },
  {
    StadiumID: 201,
    Active: true,
    Name: 'SHI Stadium',
    Dome: false,
    City: 'Piscataway',
    State: 'NJ',
    GeoLat: 40.513611,
    GeoLong: -74.465278,
  },
  {
    StadiumID: 202,
    Active: true,
    Name: 'Wilkins Stadium',
    Dome: false,
    City: 'Magnolia',
    State: 'AR',
    GeoLat: 33.28881,
    GeoLong: -93.23695,
  },
  {
    StadiumID: 203,
    Active: true,
    Name: 'Dignity Health Sports Park',
    Dome: false,
    City: 'Carson',
    State: 'CA',
    GeoLat: 33.864,
    GeoLong: -118.261,
  },
  {
    StadiumID: 204,
    Active: true,
    Name: 'Grande Stadium',
    Dome: false,
    City: 'Midland',
    State: 'TX',
    GeoLat: 31.9884,
    GeoLong: -102.1522,
  },
  {
    StadiumID: 205,
    Active: true,
    Name: 'San Angelo Stadium',
    Dome: true,
    City: 'San Angelo',
    State: 'TX',
    GeoLat: 31.430556,
    GeoLong: -100.460278,
  },
  {
    StadiumID: 206,
    Active: true,
    Name: 'Burgess-Snow Field',
    Dome: false,
    City: 'Jacksonville',
    State: 'AL',
    GeoLat: 33.820278,
    GeoLong: -85.766389,
  },
  {
    StadiumID: 207,
    Active: true,
    Name: 'Globe Life Park in Arlington',
    Dome: false,
    City: 'Arlington',
    State: 'TX',
    GeoLat: 32.751389,
    GeoLong: -97.082778,
  },
];
